// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwbx8TviIlNXOdhzSP-fBKgqyZ60Zi_4Q',
    appId: '1:97768582876:web:0195d58f6491b266bbce19',
    messagingSenderId: '97768582876',
    projectId: 'finance-ghid',
    authDomain: 'finance-ghid.firebaseapp.com',
    storageBucket: 'finance-ghid.appspot.com',
    measurementId: 'G-CMPS6W6NMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcgvX5eQYDBQIpabeshTB1wIJqZ1uCAFM',
    appId: '1:97768582876:android:e8faceefa8a9c30ebbce19',
    messagingSenderId: '97768582876',
    projectId: 'finance-ghid',
    storageBucket: 'finance-ghid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9xq6OFfQLmvn7jQ6ELT9lVGsd31YUGUw',
    appId: '1:97768582876:ios:e185dcfefd4fd61dbbce19',
    messagingSenderId: '97768582876',
    projectId: 'finance-ghid',
    storageBucket: 'finance-ghid.appspot.com',
    iosClientId: '97768582876-t2niungauoc50m5napj8j5ev6v6erq8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9xq6OFfQLmvn7jQ6ELT9lVGsd31YUGUw',
    appId: '1:97768582876:ios:efae8b39444f9e4cbbce19',
    messagingSenderId: '97768582876',
    projectId: 'finance-ghid',
    storageBucket: 'finance-ghid.appspot.com',
    iosClientId: '97768582876-pn6c5e8erm67hndd16i1u6ncgsq9cs41.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeApp.RunnerTests',
  );
}
